import { ParkingSpot, UserProfile, Review } from '../types';

export const INITIAL_PARKING_SPOTS: ParkingSpot[] = [
  {
    id: 'official-saba-borghese-rome',
    ownerId: 'official-operator-saba',
    ownerName: 'Saba Parcheggi Roma',
    ownerPhoto: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=200&q=80',
    ownerRating: 4.8,
    ownerBookingsCount: 1420,
    ownerHostStatus: 'super_host',
    title: 'Parcheggio Ufficiale Custodito Villa Borghese (Saba)',
    description: 'Parcheggio multipiano sotterraneo custodito e videosorvegliato H24 situato all\'interno di Villa Borghese con accesso diretto a Piazza di Spagna e Via Veneto. Dotato di colonnine di ricarica elettrica, varchi automatici Telepass, ascensori e personale di sicurezza presente 24 ore su 24.',
    latitude: 41.9098,
    longitude: 12.4878,
    approximateLocation: 'Villa Borghese / Piazza di Spagna, Roma',
    exactAddress: 'Viale del Galoppatoio 33, 00197 Roma',
    accessInstructions: 'Ingresso da Viale del Galoppatoio. Ritira il biglietto o usa la corsia riservata Janus con lettura targa automatica. Personale di cassa attivo 24/7 al piano -1.',
    pricePerHour: 2.80,
    pricePerDay: 22.0,
    parkingType: 'underground',
    vehicleSize: 'suv',
    supportedVehicles: ['small_car', 'standard_car', 'suv', 'motorcycle'],
    maxLength: 5.2,
    maxWidth: 2.3,
    maxHeight: 2.1,
    securityFeatures: ['closed_garage', 'automatic_gate', 'video_surveillance', 'well_lit', 'guarded', 'controlled_access'],
    accessType: 'automatic_gate',
    accessDifficulty: 'easy',
    accessNotes: 'Ampie rampe di accesso a doppio senso. Accesso agevole per ogni tipo di vettura e SUV fino a 2.10m.',
    availability: 'Aperto 24/7 H24 Continuato',
    photos: [
      'https://images.unsplash.com/photo-1590674899484-d5640e854abe?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'active',
    rating: 4.8,
    reviewCount: 184,
    completedBookings: 320,
    averageLocationRating: 4.9,
    averageSafetyRating: 4.9,
    averageAccessRating: 4.8,
    averageAccuracyRating: 4.9,
    averageConditionRating: 4.7,
    isOfficialGuarded: true,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'spot-rome-trastevere-01',
    ownerId: 'host-marco-val',
    ownerName: 'Marco Valente',
    ownerPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    ownerRating: 4.9,
    ownerBookingsCount: 37,
    ownerHostStatus: 'super_host',
    title: 'Private Garage in Trastevere with Automated Gate',
    description: 'Safe underground spot in a secure residential garage with CCTV and automated gate access. Ideal for visiting Santa Maria in Trastevere and Gianicolo hill. Clean, paved, and well illuminated.',
    latitude: 41.8885,
    longitude: 12.4705,
    approximateLocation: 'Trastevere, Rome',
    exactAddress: 'Via della Lungara 128, 00165 Roma',
    accessInstructions: 'Enter code #4492 at the main gate. Park in slot G-12. Keycard box is on the left pillar.',
    pricePerHour: 2.50,
    pricePerDay: 18.0,
    parkingType: 'garage',
    vehicleSize: 'suv',
    supportedVehicles: ['small_car', 'standard_car', 'suv'],
    maxLength: 4.9,
    maxWidth: 2.1,
    maxHeight: 2.0,
    securityFeatures: ['closed_garage', 'automatic_gate', 'video_surveillance', 'well_lit', 'controlled_access'],
    accessType: 'automatic_gate',
    accessDifficulty: 'easy',
    accessNotes: 'Slight ramp from street level. Gate opens automatically with pin code.',
    availability: 'Mon - Sun, 07:00 - 23:00',
    photos: [
      'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1590674899484-d5640e854abe?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1621929747188-0b4dc28498d2?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'active',
    rating: 4.9,
    reviewCount: 28,
    completedBookings: 37,
    averageLocationRating: 4.9,
    averageSafetyRating: 5.0,
    averageAccessRating: 4.8,
    averageAccuracyRating: 4.9,
    averageConditionRating: 4.8,
    isOfficialGuarded: false,
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'official-garage-trastevere-h24',
    ownerId: 'official-operator-trastevere',
    ownerName: 'Garage Trastevere Custodito',
    ownerPhoto: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80',
    ownerRating: 4.9,
    ownerBookingsCount: 890,
    ownerHostStatus: 'super_host',
    title: 'Garage Custodito H24 Trastevere Centro Storico',
    description: 'Autorimessa storica custodita e coperta nel cuore di Trastevere, fuori dalla ZTL durante gli orari diurni o con permesso di transito autorizzato per i clienti. Sorveglianza continua con guardiano e telecamere HD a circuito chiuso.',
    latitude: 41.8892,
    longitude: 12.4712,
    approximateLocation: 'Trastevere / Santa Maria, Roma',
    exactAddress: 'Via della Lungara 110, 00165 Roma',
    accessInstructions: 'Suona al citofono Janus o mostra il codice QR della prenotazione al custode all\'ingresso.',
    pricePerHour: 3.50,
    pricePerDay: 26.0,
    parkingType: 'garage',
    vehicleSize: 'suv',
    supportedVehicles: ['small_car', 'standard_car', 'suv', 'motorcycle'],
    maxLength: 5.0,
    maxWidth: 2.2,
    maxHeight: 2.2,
    securityFeatures: ['closed_garage', 'video_surveillance', 'guarded', 'well_lit', 'controlled_access'],
    accessType: 'host_meeting',
    accessDifficulty: 'easy',
    accessNotes: 'Ingresso diretto da Via della Lungara. Personale presente per assistenza al parcheggio.',
    availability: 'Aperto 24/7 Lunedì - Domenica',
    photos: [
      'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1590674899484-d5640e854abe?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'active',
    rating: 4.9,
    reviewCount: 142,
    completedBookings: 215,
    averageLocationRating: 4.9,
    averageSafetyRating: 5.0,
    averageAccessRating: 4.7,
    averageAccuracyRating: 4.9,
    averageConditionRating: 4.8,
    isOfficialGuarded: true,
    createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'spot-rome-prati-02',
    ownerId: 'host-elena-rossi',
    ownerName: 'Elena Rossi',
    ownerPhoto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    ownerRating: 4.8,
    ownerBookingsCount: 19,
    ownerHostStatus: 'trusted_host',
    title: 'Courtyard Covered Spot next to Vatican Museums',
    description: 'Private courtyard parking protected by electric bar and video surveillance. 4 minutes walk from Ottaviano Metro station and St. Peter’s Basilica. Perfect for day trips without blue line stress.',
    latitude: 41.9082,
    longitude: 12.4556,
    approximateLocation: 'Prati / Vatican, Rome',
    exactAddress: 'Via Ottaviano 42, 00192 Roma',
    accessInstructions: 'Call the buzzer #8 for electric gate opening. Slot marked with yellow sign PARK-02.',
    pricePerHour: 3.00,
    pricePerDay: 20.0,
    parkingType: 'covered',
    vehicleSize: 'sedan',
    supportedVehicles: ['small_car', 'standard_car'],
    maxLength: 4.7,
    maxWidth: 2.0,
    maxHeight: 2.2,
    securityFeatures: ['automatic_gate', 'video_surveillance', 'well_lit', 'controlled_access'],
    accessType: 'remote',
    accessDifficulty: 'moderate',
    accessNotes: 'Narrow archway entrance into courtyard (2.1m width). Please proceed slowly.',
    availability: 'Mon - Sat, 08:00 - 20:00',
    photos: [
      'https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1621929747188-0b4dc28498d2?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'active',
    rating: 4.8,
    reviewCount: 15,
    completedBookings: 19,
    averageLocationRating: 5.0,
    averageSafetyRating: 4.8,
    averageAccessRating: 4.6,
    averageAccuracyRating: 4.9,
    averageConditionRating: 4.7,
    isOfficialGuarded: false,
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'spot-rome-colosseo-03',
    ownerId: 'host-matteo-bianchi',
    ownerName: 'Matteo Bianchi',
    ownerPhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    ownerRating: 5.0,
    ownerBookingsCount: 8,
    ownerHostStatus: 'verified_host',
    title: 'Private Box near Colosseum & Monti district',
    description: 'Completely closed private lockbox garage in quiet alleyway. Security camera facing the entrance door. Suitable for standard cars and motorcycles. 5 min walk to Colosseum.',
    latitude: 41.8902,
    longitude: 12.4922,
    approximateLocation: 'Monti / Colosseo, Rome',
    exactAddress: 'Via Capo d\'Africa 24, 00184 Roma',
    accessInstructions: 'Smart lockbox key code 7781. Turn key right to open overhead door.',
    pricePerHour: 3.50,
    pricePerDay: 25.0,
    parkingType: 'box',
    vehicleSize: 'compact',
    supportedVehicles: ['small_car', 'motorcycle'],
    maxLength: 4.2,
    maxWidth: 1.9,
    maxHeight: 1.9,
    securityFeatures: ['closed_garage', 'video_surveillance', 'controlled_access'],
    accessType: 'key_code',
    accessDifficulty: 'moderate',
    accessNotes: 'Narrow historic Monti cobblestone alley. Turn slowly into garage box.',
    availability: '24/7 Available',
    photos: [
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'active',
    rating: 5.0,
    reviewCount: 7,
    completedBookings: 8,
    averageLocationRating: 5.0,
    averageSafetyRating: 5.0,
    averageAccessRating: 4.7,
    averageAccuracyRating: 5.0,
    averageConditionRating: 4.9,
    isOfficialGuarded: false,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'official-saba-termini-station',
    ownerId: 'official-operator-saba',
    ownerName: 'Saba Parcheggi Roma',
    ownerPhoto: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=200&q=80',
    ownerRating: 4.6,
    ownerBookingsCount: 1980,
    ownerHostStatus: 'super_host',
    title: 'Parcheggio Ufficiale Saba Stazione Roma Termini',
    description: 'Parcheggio multipiano adiacente all\'ingresso principale della Stazione Termini. Perfetto per chi prende l\'alta velocità Frecciarossa/Italo o il Leonardo Express per Fiumicino Aeroporto. Presidio costante e telecamere su tutti i livelli.',
    latitude: 41.9015,
    longitude: 12.5020,
    approximateLocation: 'Stazione Termini / Esquilino, Roma',
    exactAddress: 'Via Marsala 53, 00185 Roma',
    accessInstructions: 'Ingresso da Via Marsala. Seguire la corsia di accesso Janus automatica.',
    pricePerHour: 2.60,
    pricePerDay: 20.0,
    parkingType: 'underground',
    vehicleSize: 'van',
    supportedVehicles: ['small_car', 'standard_car', 'suv', 'large_van', 'motorcycle'],
    maxLength: 5.4,
    maxWidth: 2.4,
    maxHeight: 2.1,
    securityFeatures: ['closed_garage', 'automatic_gate', 'video_surveillance', 'well_lit', 'guarded', 'controlled_access'],
    accessType: 'automatic_gate',
    accessDifficulty: 'easy',
    accessNotes: 'Accesso comodo e diretto da Via Marsala con ampi spazi di manovra.',
    availability: 'Aperto 24/7 H24 Continuato',
    photos: [
      'https://images.unsplash.com/photo-1590674899484-d5640e854abe?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'active',
    rating: 4.6,
    reviewCount: 165,
    completedBookings: 290,
    averageLocationRating: 4.8,
    averageSafetyRating: 4.7,
    averageAccessRating: 4.6,
    averageAccuracyRating: 4.7,
    averageConditionRating: 4.5,
    isOfficialGuarded: true,
    createdAt: new Date(Date.now() - 70 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-01',
    bookingId: 'book-completed-101',
    parkingId: 'spot-rome-trastevere-01',
    hostId: 'host-marco-val',
    guestId: 'guest-alessio-t',
    guestName: 'Alessio T.',
    guestPhoto: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
    overallRating: 5.0,
    rating: 5.0,
    locationRating: 5.0,
    safetyRating: 5.0,
    accessRating: 4.9,
    accuracyRating: 5.0,
    conditionRating: 4.8,
    comment: 'Super easy access! The gate code worked on the first try and the spot is wide and clean. Saved me over an hour looking for parking in Trastevere on a Saturday night.',
    verifiedBooking: true,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'rev-02',
    bookingId: 'book-completed-102',
    parkingId: 'spot-rome-trastevere-01',
    hostId: 'host-marco-val',
    guestId: 'guest-giulia-m',
    guestName: 'Giulia M.',
    guestPhoto: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    overallRating: 4.8,
    rating: 4.8,
    locationRating: 4.9,
    safetyRating: 5.0,
    accessRating: 4.7,
    accuracyRating: 4.8,
    conditionRating: 4.9,
    comment: 'Marco is a genuine Super Host. Clear instructions and the garage felt completely safe. Will definitely book again!',
    verifiedBooking: true,
    createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
  },
  {
    id: 'rev-03',
    bookingId: 'book-completed-103',
    parkingId: 'spot-rome-prati-02',
    hostId: 'host-elena-rossi',
    guestId: 'guest-luca-f',
    guestName: 'Luca F.',
    guestPhoto: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=150&q=80',
    overallRating: 4.8,
    rating: 4.8,
    locationRating: 5.0,
    safetyRating: 4.8,
    accessRating: 4.6,
    accuracyRating: 4.9,
    conditionRating: 4.7,
    comment: 'Perfect for attending a morning meeting near the Vatican. Clean courtyard and very kind host. Notice the narrow entrance, but my sedan fitted easily.',
    verifiedBooking: true,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'rev-04',
    bookingId: 'book-completed-104',
    parkingId: 'official-saba-borghese-rome',
    hostId: 'official-operator-saba',
    guestId: 'guest-davide-b',
    guestName: 'Davide B.',
    guestPhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    overallRating: 4.9,
    rating: 4.9,
    locationRating: 5.0,
    safetyRating: 5.0,
    accessRating: 4.9,
    accuracyRating: 4.9,
    conditionRating: 4.7,
    comment: 'Top quality guarded structure. Direct tunnel walk to Piazza di Spagna. Video cameras and guards on every floor gave great peace of mind.',
    verifiedBooking: true,
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  }
];

export const DEMO_USER_PROFILE: UserProfile = {
  uid: 'demo-user-123',
  email: 'driver@janus.app',
  displayName: 'Alex Morgan',
  photoURL: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
  phoneNumber: '+39 06 1234567',
  rating: 4.9,
  reviewCount: 12,
  completedBookings: 15,
  verificationStatus: 'verified',
  hostStatus: 'trusted_host',
  emailVerified: true,
  documentVerified: true,
  idDocumentType: 'id_card',
  idDocumentNumber: 'CA84920KL',
  truthDeclarationSigned: true,
  truthDeclarationDate: '2025-05-14T10:00:00.000Z',
  createdAt: new Date(Date.now() - 120 * 86400000).toISOString(),
};
